/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package x2oracle;

import org.junit.Test;

import x2oracle.UpdateController;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testMergeNode() {
        UpdateController uc = new UpdateController();
        assertTrue("mergeNode should return 'true'", uc.someLibraryMethod());
    }
}
